services:
  web:
    build:
      context: .
    command: gunicorn -w 4 -b 0.0.0.0:8000 wsgi:app
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0

  celery_worker:
    build:
      context: .
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
